// Insprired by https://github.com/jlfwong/speedscope/blob/main/src/import/v8proflog.ts

// This imports profiles generated by a combination of the following commands:
//
//    node --prof /path/to/my/script.js
//    node --prof-process -preprocess isolate*.log > profile.v8log.json

import { V8CpuProfile, V8CpuProfileFunction, V8CpuProfileScript } from '../types.js';

interface Code {
    name: string;
    type: 'CODE' | 'CPP' | 'JS' | 'SHARED_LIB';
    timestamp?: number;
    kind?:
        | 'Bultin'
        | 'BytecodeHandler'
        | 'Handler'
        | 'KeyedLoadIC'
        | 'KeyedStoreIC'
        | 'LoadGlobalIC'
        | 'LoadIC'
        | 'Opt'
        | 'StoreIC'
        | 'Stub'
        | 'Unopt'
        | 'Builtin'
        | 'RegExp';
    func?: number;
    tm?: number;
    source?: CodeSource;
}

interface CodeSource {
    script: number;
    start: number;
    end: number;
    positions: string;
    inlined: string;
    fns: number[];
}

interface ProfileFunction {
    name: string;
    codes: number[];
}

interface Tick {
    tm: number;  // timestamp
    vm: number;  // vm state
    s: number[]; // stack
}

interface Script {
    id: number;
    url: string;
    source: string;
}

interface V8LogProfile {
    code: Code[];
    functions: ProfileFunction[];
    ticks: Tick[];
    scripts: Script[];
}

interface CodeCallFrameInfo {
    name: string;
    file?: string; // file path
    line?: number;
    col?: number;
}

type CallFrame = {
    scriptId: number;
    functionId?: number | null;
    functionName: string;
    url: string;
    lineNumber: number;
    columnNumber: number;
}
type Node = {
    id: number;
    callFrame: CallFrame;
    children: number[];
}

export const VM_STATE_JS = 0;
export const VM_STATE_GC = 1;
export const VM_STATE_OTHER = 5;
export const VM_STATE_EXTERNAL = 6;
export const VM_STATE_IDLE = 7;
export const vmState = [
    'js',
    'garbage collector',
    'parser',
    'compiler bytecode',
    'compiler',
    'other',
    'external',
    'idle',
    'atomics wait',
    'logging'
] as const;

function findBalancePair(str: string, offset: number, pattern: string) {
    const stack: string[] = [];
    for (let i = offset; i < str.length; i++) {
        if (stack.length === 0) {
            if (str[i] === pattern) {
                return i;
            }
        } else if (stack[stack.length - 1] === str[i]) {
            stack.pop();
            continue;
        }

        switch (str[i]) {
            case '<': stack.push('>'); break;
            case '(': stack.push(')'); break;
            case '[': stack.push(']'); break;
        }
    }

    return str.length;
}

function cleanupInternalName(name: string) {
    // cut off ::(anonymous namespace)
    name = name.replace(/::\(.+?\)/g, '');

    // cut off (...) and <...>
    for (let i = 0; i < name.length; i++) {
        switch (name[i]) {
            case '<':
                name = name.slice(0, i) + name.slice(findBalancePair(name, i + 1, '>') + 1);
                i--;
                break;
            case '(':
                name = name.slice(0, i) + name.slice(findBalancePair(name, i + 1, ')') + 1);
                i--;
                break;
        }
    }

    // cut off a types in prefix, i.e. void FunctionName
    const wsIndex = name.lastIndexOf(' ');
    name = wsIndex !== -1
        ? name.slice(wsIndex + 1)
        : name;

    return name;
}

function functionNameFromCode(code: Code) {
    const { name } = code;
    const spaceIndex = name.lastIndexOf(' ');
    const prelude = name.slice(0, spaceIndex);
    const functionName = prelude.startsWith('get ') ? prelude.slice(4) : prelude;

    return functionName;
}

function functionTier(kind: string) {
    switch (kind) {
        case 'Builtin':
        case 'Ignition':
        case 'Unopt':
            return 'Ignition';

        case 'Baseline':
        case 'Sparkplug':
            return 'Sparkplug';

        case 'Maglev':
            return 'Maglev';

        case 'Turboprop':
            return 'Turboprop';

        case 'Opt':
        case 'Turbofan':
            return 'Turbofan';

        default:
            return 'Unknown';
    }
}

function codeToCallFrameInfo(code: Code): CodeCallFrameInfo {
    if (!code || !code.type) {
        return {
            name: '(unknown)'
        };
    }

    let name = code.name;
    switch (code.type) {
        case 'CPP': {
            if (name[1] === ' ') {
                name = cleanupInternalName(name.slice(2));
            }
            break;
        }

        case 'SHARED_LIB': {
            // FIXME: there is no way in cpuprofile to express shared libs at the moment,
            // so represent them as (program) for now
            name = '(LIB) ' + name; // '(program)';
            break;
        }

        case 'JS': {
            const spaceIndex = name.lastIndexOf(' ');
            const prelude = name.slice(0, spaceIndex);
            const functionName = prelude.startsWith('get ') ? prelude.slice(4) : prelude;
            const url = name.slice(spaceIndex + 1);
            const locMatch = url.match(/:(\d+):(\d+)/);
            let file = url;
            let line = -1;
            let col = -1;

            if (locMatch) {
                file = url.slice(0, -locMatch[0].length);
                line = parseInt(locMatch[1], 10);
                col = parseInt(locMatch[2], 10);
            }

            if (functionName.startsWith('wasm-function')) {
                file = 'wasm://wasm/' + file;
            }

            return {
                name: functionName,
                file,
                line,
                col
            };
        }

        case 'CODE': {
            switch (code.kind) {
                case 'LoadIC':
                case 'StoreIC':
                case 'KeyedStoreIC':
                case 'KeyedLoadIC':
                case 'LoadGlobalIC':
                case 'Handler':
                    name = '(IC) ' + name;
                    break;

                case 'BytecodeHandler':
                    name = '(bytecode) ~' + name;
                    break;

                case 'Stub':
                    name = '(stub) ' + name;
                    break;

                case 'Builtin':
                    name = '(builtin) ' + name;
                    break;

                case 'RegExp':
                    name = 'RegExp: ' + name;
                    break;
            }

            break;
        }

        default: {
            name = `(${code.type}) ${name}`;
        }
    }

    return { name };
}

function createCallFrame(
    functionName: string,
    url = '',
    lineNumber = -1,
    columnNumber = -1,
    scriptId = 0,
    functionId: number | null = null
): CallFrame {
    return {
        scriptId,
        functionId,
        functionName,
        url,
        lineNumber,
        columnNumber
    };
}

function createNode(id: number, callFrame: CallFrame): Node {
    return {
        id,
        callFrame,
        children: []
    };
}

export function isV8Log(data: Record<string, unknown>) {
    if (
        data && typeof data === 'object' &&
        Array.isArray(data.code) &&
        Array.isArray(data.functions) &&
        Array.isArray(data.ticks)) {
        return true;
    }

    return false;
}

export function convertV8LogIntoCpuprofile(v8log: V8LogProfile): V8CpuProfile {
    const scriptIdByUrl = new Map<string, number>([['', 0]]);
    const getScriptIdByUrl = (url: string) => scriptIdByUrl.has(url)
        ? scriptIdByUrl.get(url)
        : scriptIdByUrl.set(url, scriptIdByUrl.size).size - 1;
    const vmStateCallFrames = vmState.map(name =>
        name !== 'js' && name !== 'other' && name !== 'external'
            ? createCallFrame(`(${name})`)
            : null
    );
    const rootCallFrame = createCallFrame('(root)');
    const idleCallFrame = createCallFrame('(idle)');
    const callFrameById = new Map<number, CallFrame>();
    const rootNode = createNode(1, rootCallFrame);
    const rootNodeMap = new Map();
    const nodes = [rootNode];
    const nodesTransition = new Map<number, Map<CallFrame, Node>>([[1, rootNodeMap]]);
    let nodeIdSeed = 1;
    let lastTm = 0;
    const scripts: V8CpuProfileScript[] = [];
    const functions: V8CpuProfileFunction[] = [];
    const profile: V8CpuProfile = {
        startTime: 0,
        endTime: 0,
        nodes,
        timeDeltas: new Array(v8log.ticks.length),
        samples: new Array(v8log.ticks.length),
        scripts,
        functions
    };

    v8log.ticks.sort((a, b) => a.tm - b.tm);

    for (let tickIndex = 0; tickIndex < v8log.ticks.length; tickIndex++) {
        const tick = v8log.ticks[tickIndex];
        let vmStateCallFrame = vmStateCallFrames[tick.vm];
        let currentNode = rootNode;
        let currentNodeMap = rootNodeMap;

        if (vmStateCallFrame === null || tick.vm !== VM_STATE_GC) {
            for (let i = tick.s.length - 2; i >= 0; i -= 2) {
                const id = tick.s[i];

                if (id === -1) {
                    continue;
                }

                let callFrame = callFrameById.get(id);

                if (callFrame === undefined) {
                    if (id > v8log.code.length) {
                        // treat unknown ids as a memory address
                        callFrame = createCallFrame(`0x${id.toString(16)}`);
                    } else {
                        const code = v8log.code[id];

                        // FIXME: ignore Abort.Wide/ExtraWide for now since it too noisy;
                        // not sure was it stands for, but looks like an execution pause
                        if (code.kind === 'BytecodeHandler') {
                            if (code.name === 'Abort.Wide' || code.name === 'Abort.ExtraWide') {
                                continue;
                            }
                        }

                        const { name, file, line, col } = codeToCallFrameInfo(code);
                        callFrame = createCallFrame(
                            name,
                            file,
                            line,
                            col,
                            code.source ? code.source.script : getScriptIdByUrl(file || ''),
                            typeof code.func === 'number' ? code.func : null
                        );
                    }

                    callFrameById.set(id, callFrame);
                }

                let nextNode = currentNodeMap.get(callFrame);

                if (nextNode === undefined) {
                    nextNode = createNode(++nodeIdSeed, callFrame);
                    nodes.push(nextNode);
                    currentNodeMap.set(callFrame, nextNode);
                    currentNode.children.push(nextNode.id);
                    nodesTransition.set(nodeIdSeed, currentNodeMap = new Map());
                } else {
                    currentNodeMap = nodesTransition.get(nextNode.id) as Map<CallFrame, Node>;
                }

                currentNode = nextNode;
            }
        }

        // console.log(vmState[tick.vm] || 'unknown', currentNode === rootNode, v8log.code[tick.s[0]], tick);
        if (vmStateCallFrame === null && currentNode === rootNode) {
            vmStateCallFrame = idleCallFrame;
        }

        if (vmStateCallFrame !== null) {
            let node = currentNodeMap.get(vmStateCallFrame);

            if (node === undefined) {
                node = createNode(++nodeIdSeed, vmStateCallFrame);
                nodes.push(node);
                currentNodeMap.set(vmStateCallFrame, node);
                currentNode.children.push(node.id);
                nodesTransition.set(nodeIdSeed, new Map());
            }

            currentNode = node;
        }

        profile.samples[tickIndex] = currentNode.id;
        profile.timeDeltas[tickIndex] = tick.tm - lastTm;

        lastTm = tick.tm;
    }

    profile.endTime =
        lastTm +
        profile.timeDeltas.slice().sort()[profile.timeDeltas.length >> 1];

    const scriptIdToIndex = new Map<number, number>();
    for (const { id, url, source } of v8log.scripts.filter(Boolean)) {
        scriptIdToIndex.set(id, scripts.length);
        scripts.push({
            id,
            url,
            source
        });
    }

    for (let i = 0; i < v8log.functions.length; i++) {
        const fn = v8log.functions[i];
        const code = v8log.code[fn.codes[0]];
        const source = code.source as CodeSource;
        const loc = code.name.match(/\:(\d+)\:(\d+)/);

        if (!source) {
            // wasm functions has no source
            // console.log(fn, fn.codes.map(x => v8log.code[x]));
            continue;
        }

        functions.push({
            id: i,
            name: functionNameFromCode(code),
            script: scriptIdToIndex.get(source.script) ?? null,
            start: source.start,
            end: source.end,
            line: loc ? Number(loc[1]) : -1,
            column: loc ? Number(loc[2]) : -1,
            states: fn.codes.map(codeIndex => {
                const code = v8log.code[codeIndex];

                return {
                    tm: code.tm || 0,
                    tier: functionTier(code.kind || 'Unknown'),
                    positions: source?.positions || '',
                    inlined: source?.inlined || '',
                    fns: source?.fns || []
                };
            })
        });
    }

    return profile;
}
